# Generated by Django 2.2.8 on 2019-12-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
